## Comic (xkcd-like) phylogenetic tree {#commicR}

```{r include=F}
library("yulab.utils")
source("software-link.R")

# https://github.com/timelyportfolio/comicR
if (!is.installed("comicR"))
    remotes::install_github("timelyportfolio/comicR")
```

```{r ggsvg, fig.show='hide'}
library(htmltools)    
library(XML)    
library(gridSVG)    
library(ggplot2)    
library(ggtree)
library(comicR)    

p <- ggtree(rtree(30), layout="circular")  +
    geom_tiplab(aes(label=label), color="purple")
print(p)
svg <- grid.export(name="", res=100)$svg
```

(ref:comicRscap) Remove image background.

(ref:comicRcap) **Remove image background.** Plotting silhouette images on phylogenetic tree without (A) and with (B) background remove.


```{r comicR, eval=FALSE} 
## need to convert it to png or pdf for pdfbook
tagList(
    tags$div(
             id = "ggtree_comic",
             tags$style("#ggtree_comic text {font-family:Chalkduster;}"),
             HTML(saveXML(svg)),
             comicR("#ggtree_comic", ff=5)
         )
) # %>% html_print()
```
